### ISSUE TITLE
Milestone 4

### ISSUE THREAD

**Issue by philkra** [xataio/xata-go#6]
- [x] [list branches](https://xata.io/docs/api-reference/dbs/db_name#list-branches): `GET /dbs/{db_name}`
  - [x] [get branch details](https://xata.io/docs/api-reference/db/db_branch_name#get-branch-schema-and-metadata): `GET /db/{db_branch_name}`
  - [x] [create branch](https://xata.io/docs/api-reference/db/db_branch_name#create-database-branch): `PUT /db/{db_branch_name}`
  - [x] [delete a branch](https://xata.io/docs/api-reference/db/db_branch_name#delete-database-branch): `DELETE /db/{db_branch_name}`
  - [x] [list databases](https://xata.io/docs/api-reference/workspaces/workspace_id/dbs#list-databases): `GET /workspaces/{workspace_id}/dbs`
  - [x] [rename a database](https://xata.io/docs/api-reference/workspaces/workspace_id/dbs/db_name/rename#rename-database): `POST /workspaces/{workspace_id}/dbs/{db_name}/rename`
  - [x] [get workspace](https://xata.io/docs/api-reference/workspaces/workspace_id#get-an-existing-workspace): `GET /workspaces/{workspace_id}`
  - [x] [update workspace](https://xata.io/docs/api-reference/workspaces/workspace_id#update-an-existing-workspace): `PUT /workspaces/{workspace_id}`
  - [x] [get current user](https://xata.io/docs/api-reference/user#get-user-details): `GET /user`
  - [x] [get table schema](https://xata.io/docs/api-reference/db/db_branch_name/tables/table_name/schema#get-table-schema): `GET /db/{db_branch_name}/tables/{table_name}/schema`
  - [x] [get table columns](https://xata.io/docs/api-reference/db/db_branch_name/tables/table_name/columns#list-table-columns): `GET /db/{db_branch_name}/tables/{table_name}/columns`

```[tasklist]
### Tasks
- [ ] https://github.com/xataio/xata-go/pull/10
- [ ] https://github.com/xataio/xata-go/pull/9
- [ ] https://github.com/xataio/xata-go/pull/12
- [ ] https://github.com/xataio/xata-go/pull/13
```
